import turtle as t
t.speed(0)
t.delay(0)

def kwadtar():
    t.pencolor('orange')
    t.fillcolor('orange')
    t.begin_fill()
    for x in range(4):
        t.fd(10)
        t.lt(90)
    t.end_fill()

def linia(ile):
    for x in range(ile):
        kwadtar()
        t.pu()
        t.fd(10)
        t.pd()

t.pu()
t.lt(90)
t.bk(200)
t.lt(90)
t.fd(200)
t.rt(180)
t.pd()

def organy(ile):
    dlugosc = int((480-40)/10)
    poz_start = t.pos()
    linia(3)
    t.lt(90)
    for x in range(ile//2+1):
        linia(dlugosc)
        t.bk(10)
        t.rt(90)
        t.bk(10)
        linia(3)
        t.bk(10)
        t.rt(90)
        t.bk(10)
        linia(dlugosc)
        t.lt(90)
        linia(3)
        t.lt(90)
        dlugosc-=3
    dlugosc += 3
    for x in range(ile//2):
        dlugosc += 3
        linia(dlugosc)
        t.bk(10)
        t.rt(90)
        t.bk(10)
        linia(3)
        t.bk(10)
        t.rt(90)
        t.bk(10)
        linia(dlugosc)
        t.lt(90)
        linia(3)
        t.lt(90)

    t.pu()
    t.goto(poz_start)
    t.fd(20)
    t.rt(90)
    t.fd(10)
    t.lt(90)
    t.pd()
    dlugosc = int((480 - 20) / 10)
    linia(dlugosc)
    t.bk(10)
    t.rt(90)
    t.bk(10)
    poz_start = t.pos()
    linia(ile+((ile//2+1)*2))
    t.pu()
    t.fd(10)
    t.pd()
    linia(ile+((ile//2+1)*2))
    t.bk(10)
    t.rt(90)
    t.bk(10)
    linia(dlugosc)
    t.pu()
    t.goto(poz_start)
    t.fd(20)
    t.lt(90)
    t.pu()
    t.fd(20)
    t.pd()
    linia((ile*3)+(ile-1))

linia(20)
t.done()